# name: Deploy2

# # Trigger the workflow on push and
# # pull request events on the production branch
# on:
#   push:
#     branches:
#       - production
#       - master
#   pull_request:
#     branches:
#       - production

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#       name: Compile CSS and Javascript
#       run: |
#           npm ci
#           npm run prod
#     - uses: shivammathur/setup-php@master
#       name: Configure PHP 8.0
#       with:
#         php-version: 8.0
#         extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml

